import {PILOT_LIMITS} from '@/lib/plans';
import {randomUUID} from 'node:crypto';
import {requireUser,checkOrigin,consumeLimit} from '@/lib/auth';
import {AppError,getLibrary,getMaterial,saveMaterial,applyMaterialResult,importMaterialTopics,saveAssessment,getChat,mutateLibrary,writeObject,readObject,fileStream,removeObject,materialPath,userPath,card,safeId} from '@/lib/storage';
import {body,json,route} from '@/lib/http';import {inspectFile,extractPDF,MAX_UPLOAD} from '@/lib/files';import {generateStudy,deriveConcepts,assessAnswer,requireCurrentStudy,extractWithAI,answerFromMaterials} from '@/lib/ai';import type {Material,Topic} from '@/lib/types';
export const maxDuration=120;export const dynamic='force-dynamic';
const cleanMaterial=(m:Material)=>{const {filePath,...rest}=m;return rest};
type Context={params:Promise<{path:string[]}>};
export async function GET(request:Request,{params}:Context){return route(async()=>{const {path}=await params;const user=await requireUser();if(path[0]==='export'){const lib=await getLibrary(user.id);let index=-1;const encoder=new TextEncoder();const stream=new ReadableStream({async pull(controller){try{if(index===-1){controller.enqueue(encoder.encode(JSON.stringify({version:1,exportedAt:new Date().toISOString()}).slice(0,-1)+',"materials":['));index=0;return}if(index<lib.materials.length){const material=cleanMaterial((await getMaterial(user.id,lib.materials[index].id)).value);controller.enqueue(encoder.encode((index?',':'')+JSON.stringify(material)));index++;return}if(index<lib.materials.length+(lib.chats||[]).length){const chatIndex=index-lib.materials.length;if(chatIndex===0)controller.enqueue(encoder.encode('],"chats":['));const chat=(await getChat(user.id,lib.chats![chatIndex].id)).value;controller.enqueue(encoder.encode((chatIndex?',':'')+JSON.stringify(chat)));index++;return}controller.enqueue(encoder.encode((lib.chats?.length?']':'],"chats":[]')+',"topics":'+JSON.stringify(lib.topics)+',"reviews":'+lib.reviews+'}'));controller.close()}catch(error){controller.error(error)}}});return new Response(stream,{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="polka-export.json"','Cache-Control':'no-store'}})}if(path[0]!=='materials'||!path[1])throw new AppError('Не найдено',404);const {value:m}=await getMaterial(user.id,path[1]);if(path[2]==='file'){if(!m.filePath)throw new AppError('Оригинал не найден',404);const result=await fileStream(m.filePath,request.headers.get('range'));if(!result)throw new AppError('Оригинал не найден',404);return new Response(result.stream,{status:result.contentRange?206:200,headers:{...(result.contentRange?{'Content-Range':result.contentRange}:{}),'Accept-Ranges':'bytes','X-Frame-Options':'SAMEORIGIN','Content-Type':m.mime||'application/octet-stream','Content-Disposition':`${m.kind==='text'?'attachment':'inline'}; filename*=UTF-8''${encodeURIComponent(m.filename||'material')}`,'X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'",'Cache-Control':'private, no-store'}})}return json({material:cleanMaterial(m)})})}
export async function POST(request:Request,{params}:Context){return route(async()=>{checkOrigin(request);const user=await requireUser();const {path}=await params;
 if(path[0]==='materials'&&!path[1]){await consumeLimit('upload:'+user.id,30,3600000);if((await getLibrary(user.id)).materials.length>=PILOT_LIMITS.materials)throw new AppError('Лимит 100 материалов. Удалите ненужные.');const id=randomUUID();let title='',subject='',text='',filename:string|undefined,bytes:Buffer|undefined;let kind:Material['kind']='text',mime:string|undefined,staged:string|undefined;
 if(request.headers.get('content-type')?.includes('multipart/form-data')){if(Number(request.headers.get('content-length'))>4*1024*1024)throw new AppError('Для этого способа загрузки максимум 4 МБ.',413);const form=await request.formData();title=String(form.get('title')||'');subject=String(form.get('subject')||'');const file=form.get('file');if(!(file instanceof File)||!file.size||file.size>4*1024*1024)throw new AppError('Выберите файл до 4 МБ.');filename=file.name.slice(0,200);bytes=Buffer.from(await file.arrayBuffer());({kind,mime}=inspectFile(bytes,filename));}
 else{const input=await body(request);title=String(input.title||'');subject=String(input.subject||'');text=String(input.text||'').trim();if(input.upload){const upload=input.upload;if(typeof upload.pathname!=='string'||!upload.pathname.startsWith(`${userPath(user.id)}/uploads/`)||!upload.pathname.endsWith('.bin'))throw new AppError('Файл не принадлежит вашему аккаунту.',403);const lib=await getLibrary(user.id);if(!lib.uploads?.some(x=>x.pathname===upload.pathname))throw new AppError('Сессия загрузки истекла. Загрузите файл снова.');const stored=await readObject(upload.pathname);if(!stored||stored.data.length>MAX_UPLOAD)throw new AppError('Файл не найден или слишком большой.');bytes=stored.data;staged=upload.pathname;filename=String(upload.filename||'').slice(0,200);({kind,mime}=inspectFile(bytes,filename));}}
 if(text.length>120000)throw new AppError('Максимум 120 000 символов. Разделите материал.');if(!text&&!bytes)throw new AppError('Добавьте текст или файл.');if(!bytes&&text){bytes=Buffer.from(text);filename=(title.trim().slice(0,160)||'material')+'.txt';mime='text/plain'}const now=new Date().toISOString();const m:Material={id,title:title.trim().slice(0,160)||filename?.replace(/\.[^.]+$/,'')||text.split('\n')[0].slice(0,80),subject:subject.trim().slice(0,80)||'Без предмета',kind,createdAt:now,updatedAt:now,status:'inbox',excerpt:'',hasFile:!!bytes,filename,text,summary:'',terms:[],questions:[],mime,size:bytes?.length,sourceVersion:1,revision:1};
 if(bytes){m.filePath=`${userPath(user.id)}/files/${id}.bin`;await writeObject(m.filePath,bytes,{createOnly:true,contentType:mime});if(kind==='text'){m.text=bytes.toString('utf8');if(m.text.length>120000){await removeObject(m.filePath);if(staged)await removeObject(staged);throw new AppError('Максимум 120 000 символов в текстовом файле. Разделите его.')}}m.warning=kind==='text'?undefined:'Оригинал сохранён. Нажмите «Распознать», чтобы получить текст.'}
 try{await saveMaterial(user.id,m,undefined,staged)}catch(e){if(m.filePath)await removeObject(m.filePath);await removeObject(materialPath(user.id,m.id));throw e}finally{if(staged)await removeObject(staged).catch(()=>console.error("Temporary upload cleanup deferred"))}return json({material:cleanMaterial(m)},201)}
 if(path[0]==='materials'&&path[1]){
  const old=await getMaterial(user.id,path[1]);let m=old.value;
  if(path[2]==='topics'){
   requireCurrentStudy(m);
   if(m.concepts===undefined){const concepts=await deriveConcepts(m,user.id);if(!concepts.length)throw new AppError('В источнике не найдены понятия с точными подтверждающими цитатами.');m=await applyMaterialResult(user.id,m,{concepts,terms:concepts.map(concept=>concept.title)})}
   const imported=await importMaterialTopics(user.id,m);return json({...imported,material:cleanMaterial(imported.material)});
  }
  if(path[2]==='assess'){
   const input=await body(request);if(typeof input.answer!=='string')throw new AppError('Напишите самостоятельный ответ.');
   const assessment=await assessAnswer(m,input.questionIndex,input.answer.trim(),user.id);await saveAssessment(user.id,m,assessment);return json({assessment});
  }
  if(path[2]==='generate'){
   if(!m.text.trim())throw new AppError('Сначала распознайте или добавьте текст.');
   const study=await generateStudy(m,user.id);m={...m,...study,summaryVersion:m.sourceVersion,aiGenerated:true,status:'ready',updatedAt:new Date().toISOString()};
  }else if(path[2]==='extract'){
   if(!m.filePath)throw new AppError('Файл не найден');const file=await readObject(m.filePath);if(!file)throw new AppError('Оригинал не найден',404);let text='';
   if(m.kind==='pdf'){try{text=await extractPDF(file.data)}catch(e){if(e instanceof AppError)throw e}if(text.replace(/\[Страница \d+\]/g,'').trim().length<30)text=await extractWithAI(file.data,m,user.id)}else if(m.kind==='text')text=file.data.toString('utf8');else text=await extractWithAI(file.data,m,user.id);
   m={...m,text,sourceVersion:m.sourceVersion+1,summary:'',summaryVersion:undefined,aiGenerated:false,concepts:undefined,questions:[],terms:[],status:'inbox',warning:undefined,updatedAt:new Date().toISOString()};
  }else throw new AppError('Не найдено',404);
  m.revision=(old.value.revision||1)+1;if(m.text.length>120000)throw new AppError('Распознанный текст слишком большой. Разделите материал.');
  const saved=await applyMaterialResult(user.id,old.value,{text:m.text,summary:m.summary,terms:m.terms,concepts:m.concepts,questions:m.questions,status:m.status,sourceVersion:m.sourceVersion,summaryVersion:m.summaryVersion,aiGenerated:m.aiGenerated,warning:m.warning});return json({material:cleanMaterial(saved)});
 }
 if(path[0]==='topics'){const input=await body(request);const title=String(input.title||'').trim().slice(0,160),topicBody=String(input.body||'').trim();if(!title||!topicBody||topicBody.length>10000)throw new AppError('Укажите название и объяснение (до 10 000 символов).');if(typeof input.materialId!=='string')throw new AppError('Укажите источник.');await getMaterial(user.id,input.materialId);const topic:Topic={id:randomUUID(),title,body:topicBody,materialId:input.materialId,createdAt:new Date().toISOString()};await mutateLibrary(user.id,lib=>{if(lib.topics.length>=PILOT_LIMITS.topics)throw new AppError('Лимит 200 тем.');lib.topics.unshift(topic)});return json({topic},201)}
 if(path[0]==='review'){const input=await body(request);await getMaterial(user.id,String(input.materialId));if(!Number.isInteger(input.score)||!Number.isInteger(input.total)||input.score<0||input.total<1||input.score>input.total||input.total>8)throw new AppError('Некорректный результат теста.');await mutateLibrary(user.id,lib=>{lib.reviews++});return json({ok:true})}
 if(path[0]==='assistant'){const input=await body(request);const question=String(input.question||'').trim();if(!question||question.length>1000)throw new AppError('Вопрос должен содержать от 1 до 1000 символов.');const lib=await getLibrary(user.id);const ids=Array.isArray(input.materialIds)&&input.materialIds.length?input.materialIds.slice(0,8):lib.materials.slice(0,8).map(m=>m.id);const materials=await Promise.all(ids.map(async(id:string)=>(await getMaterial(user.id,id)).value));return json(await answerFromMaterials(question,materials,user.id))}throw new AppError('Не найдено',404)})}
export async function PATCH(request:Request,{params}:Context){return route(async()=>{checkOrigin(request);const user=await requireUser();const {path}=await params;if(path[0]!=='materials'||!path[1])throw new AppError('Не найдено',404);const old=await getMaterial(user.id,path[1]);const input=await body(request);if(input.expectedRevision!==undefined&&input.expectedRevision!==(old.value.revision||1))throw new AppError('Материал уже изменён в другой вкладке. Обновите его перед сохранением.',409);const m={...old.value};if(input.title!==undefined)m.title=String(input.title).trim().slice(0,160)||m.title;if(input.subject!==undefined)m.subject=String(input.subject).trim().slice(0,80)||'Без предмета';if(input.text!==undefined){const text=String(input.text);if(text.length>120000)throw new AppError('Максимум 120 000 символов.');if(text!==m.text){m.text=text;m.sourceVersion++;m.summary='';m.terms=[];m.concepts=undefined;m.questions=[];m.summaryVersion=undefined;m.aiGenerated=false;m.status='inbox'}}if(input.summary!==undefined)m.summary=String(input.summary).slice(0,20000);m.updatedAt=new Date().toISOString();m.revision=(old.value.revision||1)+1;if(m.text.length>120000)throw new AppError('Распознанный текст слишком большой. Разделите материал.');await saveMaterial(user.id,m,old.etag);return json({material:cleanMaterial(m)})})}
export async function DELETE(request:Request,{params}:Context){return route(async()=>{checkOrigin(request);const user=await requireUser();const {path}=await params;const id=safeId(path[1]||'');if(path[0]==='materials'){const old=await getMaterial(user.id,id);await mutateLibrary(user.id,lib=>{lib.materials=lib.materials.filter(x=>x.id!==id);lib.topics=lib.topics.filter(x=>x.materialId!==id)});await removeObject(materialPath(user.id,id));if(old.value.filePath)await removeObject(old.value.filePath);return json({ok:true})}if(path[0]==='topics'){await mutateLibrary(user.id,lib=>{lib.topics=lib.topics.filter(x=>x.id!==id)});return json({ok:true})}throw new AppError('Не найдено',404)})}
