"use client";
import OrderHistory from '@/components/billing/order-history';

import { ArrowDownToLine, ArrowUpRight, Bot, Check, Copy, HardDrive, Library, LoaderCircle, LogOut, Mail, RefreshCw, ShieldCheck, Smartphone } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import type { AccountSummary as Account } from "@/lib/types";
import { InstallApp } from "@/components/pwa/install-app";

type Meter = { used: number; limit: number };
type Props = { username: string; busy: string; exportData: () => void; logout: () => void };
const bytes = (value: number) => value === 0 ? "0 МБ" : value < 1024 * 1024 ? `${Math.ceil(value / 1024)} КБ` : value >= 1024 * 1024 * 1024 ? `${(value / 1024 / 1024 / 1024).toFixed(1)} ГБ` : `${(value / 1024 / 1024).toFixed(1)} МБ`;
function UsageMeter({ label, value, storage = false }: { label: string; value: Meter; storage?: boolean }) {
  return <div className="usage-meter"><div><span>{label}</span><strong>{storage ? bytes(value.used) : value.used} <span>из {storage ? bytes(value.limit) : value.limit}</span></strong></div><progress value={value.used} max={Math.max(1, value.limit)} aria-label={label} /><span className="meter-hint">{value.used >= value.limit ? "Лимит достигнут" : storage ? `${bytes(Math.max(0, value.limit - value.used))} свободно` : `${Math.max(0, value.limit - value.used)} осталось`}</span></div>;
}
export default function AccountPage({ username, busy, exportData, logout }: Props) {
  const [account, setAccount] = useState<Account | null>(null);
  const [loading, setLoading] = useState(true);
  const [copiedId, setCopiedId] = useState(false);
  useEffect(() => { if (!copiedId) return; const timer = setTimeout(() => setCopiedId(false), 2000); return () => clearTimeout(timer); }, [copiedId]);
  async function copyId() { if (!account) return; try { await navigator.clipboard.writeText(account.user.id); setCopiedId(true); } catch { setError("Не удалось скопировать ID. Вы можете выделить его вручную."); } }
  const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/account", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Не удалось загрузить аккаунт."); setAccount(data); } catch (reason) { setError(reason instanceof Error ? reason.message : "Аккаунт недоступен."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <div className="account-page"><header className="page-heading"><div><span className="eyebrow">ЛИЧНОЕ ПРОСТРАНСТВО</span><h1>polka.id</h1><p>Доступ, использование и ваши данные.</p></div><button className="button subtle" disabled={loading} onClick={load}><RefreshCw size={16} />Обновить</button></header>{error ? <div className="notice error-notice" role="alert">{error}<button onClick={load}>Повторить</button></div> : null}
    <div className="account-grid"><section className="account-card profile-section"><div className="account-profile"><span className="avatar avatar-large">{username.slice(0, 1).toUpperCase()}</span><div><h2>{username}</h2><p>Личная учебная библиотека</p></div><span className="access-badge"><Check size={14} />{account?.access.status === "expired" ? "Период завершён" : "Активен"}</span></div>{account ? <div className="polka-identity"><code>{account.user.id}</code><button onClick={copyId} aria-label="Скопировать идентификатор polka.id">{copiedId ? <Check size={14} /> : <Copy size={14} />}{copiedId ? "Скопировано" : "Копировать ID"}</button></div> : null}<div className="account-access"><div><span className="eyebrow">ТЕКУЩИЙ ДОСТУП</span><h3>{account ? account.access.kind === "subscription" ? account.access.paid ? "Подписка активна" : "Подписка завершена" : "Бесплатный тестовый доступ" : "Ваш доступ"}</h3><p>{account?.access.endsAt ? `Оплаченный период до ${new Intl.DateTimeFormat("ru", {day:"numeric",month:"long",year:"numeric",timeZone:"Europe/Moscow"}).format(new Date(account.access.endsAt))}. ${account.access.status === "expired" ? "Чтение и экспорт сохранены." : "Продление вручную."}` : account ? "Ваши действующие возможности показаны ниже." : "Загружаем сведения о доступе…"}</p></div><a className="button" href={account?.access.billingEnabled ? "/checkout" : "/pricing"}>{account?.access.billingEnabled ? account.access.paid ? "Продлить · 399 ₽" : "Подключить · 399 ₽" : "Тариф и условия"} <ArrowUpRight size={16} /></a></div><p className="account-footnote"><ShieldCheck size={15} />Доступ к вашей библиотеке защищён авторизацией.</p>{account?.owner ? <a className="button subtle" href="/admin"><ShieldCheck size={16}/>Панель владельца <ArrowUpRight size={16}/></a> : null}</section>
      <section className="account-card usage-section"><div className="account-section-title"><HardDrive size={20} /><div><h2>Использование</h2><p>Актуальные лимиты вашего аккаунта.</p></div></div>{loading && !account ? <div className="account-loading"><LoaderCircle className="spin" size={20} />Загружаем данные…</div> : account ? <><UsageMeter label="Материалы" value={account.usage.materials} /><UsageMeter label="Хранилище" value={account.usage.storage} storage /><UsageMeter label="Запуски ИИ за 30 дней" value={{ used: account.usage.ai.periodUsed, limit: account.usage.ai.periodLimit }} /><p className="account-footnote">{account.usage.ai.periodResetsAt ? `Период завершится ${new Intl.DateTimeFormat("ru", { day: "numeric", month: "long", timeZone: "Europe/Moscow" }).format(new Date(account.usage.ai.periodResetsAt))}.` : "30-дневный период начнётся с первого запуска ИИ."}</p><UsageMeter label="Запуски ИИ сегодня" value={account.usage.ai} /><p className="account-footnote">Дневной лимит обновится {new Intl.DateTimeFormat("ru", { day: "numeric", month: "long", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Moscow" }).format(new Date(account.usage.ai.resetsAt))} МСК. {account.usage.storage.reservedBytes > 0 ? `${bytes(account.usage.storage.reservedBytes)} зарезервировано для загрузок.` : ""}</p><p className="account-footnote">Запуск ИИ — обработка файла, создание конспекта ответ помощника или проверка вашего ответа. Извлечение готового текстового слоя PDF не расходует лимит ИИ.</p><div className="account-mini-stats"><span><Library size={15} />{account.usage.topics.used} понятий</span><span><Bot size={15} />{account.usage.chats.used} диалогов</span><span>{account.usage.reviews.used} повторений</span></div></> : <p className="muted">Данные об использовании пока недоступны.</p>}</section>
      <section className="account-card"><div className="account-section-title"><Smartphone size={20} /><div><h2>polka на телефоне</h2><p>Открывайте библиотеку как приложение.</p></div></div><InstallApp /></section>
      <section className="account-card"><div className="account-section-title"><ArrowDownToLine size={20} /><div><h2>Ваши данные</h2><p>Сохраните копию учебной библиотеки.</p></div></div><button className="button full" disabled={!!busy} onClick={exportData}>{busy === "export" ? <LoaderCircle size={17} className="spin" /> : <ArrowDownToLine size={17} />}{busy === "export" ? "Готовим экспорт…" : "Скачать библиотеку · JSON"}</button><p className="account-footnote">Тексты, понятия, история чатов и результаты повторений. Оригинальные файлы скачиваются отдельно со страниц материалов.</p></section>
      <OrderHistory />
      <section className="account-card account-wide support-section"><div className="account-section-title"><Mail size={20} /><div><h2>Нужна помощь?</h2><p>Проблема с доступом, вопрос о материалах или предложение.</p></div></div><a className="button" href="mailto:polka.sluzhbazaboty@yandex.ru">Написать в поддержку <ArrowUpRight size={16} /></a></section>
    </div><div className="account-bottom"><div><a href="/offer">Оферта</a><a href="/privacy">Конфиденциальность</a><a href="/payment">Оплата и возврат</a></div><button className="button subtle" disabled={!!busy} onClick={logout}>{busy === "logout" ? <LoaderCircle className="spin" size={16} /> : <LogOut size={16} />}Выйти из аккаунта</button></div>
  </div>;
}
