"use client";
import {useEffect,useState} from 'react';
import {ArrowRight,Check,GraduationCap,LoaderCircle,Sparkles} from 'lucide-react';
import type {Material} from '@/lib/types';
import {PILOT_LIMITS} from '@/lib/plans';

type Assessment={score:number;verdict:'correct'|'partial'|'incorrect';feedback:string;missing:string[];sourceQuote:string};
async function post<T>(url:string,data:unknown):Promise<T>{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Не удалось выполнить действие.');return result}
export default function QuizSession({material,exit,openMaterial,saved}:{material:Material;exit:()=>void;openMaterial:(id:string)=>void;saved:()=>Promise<void>}){
 const [index,setIndex]=useState(0),[answer,setAnswer]=useState(''),[revealed,setRevealed]=useState(false),[assessment,setAssessment]=useState<Assessment|null>(null),[score,setScore]=useState(0),[done,setDone]=useState(false),[isSaved,setSaved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const question=material.questions[index];
 useEffect(()=>{const frame=requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'instant'}));return()=>cancelAnimationFrame(frame)},[index,done]);
 async function assess(){setBusy(true);setError('');try{const result=await post<{assessment:Assessment}>(`/api/materials/${material.id}/assess`,{questionIndex:index,answer});setAssessment(result.assessment);setRevealed(true)}catch(reason){setError(reason instanceof Error?reason.message:'Проверка недоступна.')}finally{setBusy(false)}}
 function next(correct:boolean){setScore(value=>value+(correct?1:0));if(index+1===material.questions.length){setDone(true);return}setIndex(value=>value+1);setAnswer('');setRevealed(false);setAssessment(null);setError('')}
 async function save(){setBusy(true);setError('');try{await post('/api/review',{materialId:material.id,score,total:material.questions.length});setSaved(true);await saved()}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось сохранить.')}finally{setBusy(false)}}
 return <section className="quiz-card panel">{error?<div className="notice error-notice" role="alert">{error}</div>:null}{done?<div className="quiz-result"><span className="result-icon"><GraduationCap size={38}/></span><span className="eyebrow">ПОВТОРЕНИЕ ЗАВЕРШЕНО</span><h2>{score} из {material.questions.length}</h2><p>Ответы с понятным смыслом засчитаны. Вернитесь к сложным местам и попробуйте ещё раз. Это самопроверка, а не экзаменационная оценка.</p><div className="quiz-result-actions"><button className="button primary" disabled={busy||isSaved} onClick={save}>{isSaved?<><Check size={17}/>Результат сохранён</>:busy?'Сохраняем…':'Сохранить результат'}</button><button className="button" onClick={()=>openMaterial(material.id)}>Открыть конспект</button><button className="text-button" onClick={exit}>Другой материал <ArrowRight size={16}/></button></div></div>:<>
  <div className="quiz-meta"><span>{material.title}</span><span>{index+1} / {material.questions.length}</span></div><div className="progress-track"><span style={{width:`${((index+1)/material.questions.length)*100}%`}}/></div><h2>{question.question}</h2>
  <label>Ваш ответ<textarea value={answer} onChange={event=>{setAnswer(event.target.value);setAssessment(null);setRevealed(false)}} placeholder="Объясните своими словами. Дословное совпадение не требуется." rows={4} maxLength={4000} disabled={busy}/></label>
  {!revealed?<div className="quiz-actions"><button className="button primary" disabled={busy||!answer.trim()} onClick={assess}>{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>} {busy?'Сравниваем с лекцией…':'Проверить ответ с ИИ'}</button><button className="button" disabled={busy} onClick={()=>setRevealed(true)}>Показать разбор</button></div>:<>
   {assessment?<div className={`answer-assessment assessment-${assessment.verdict}`} role="status"><div><Sparkles size={18}/><strong>{assessment.verdict==='correct'?'Смысл передан верно':assessment.verdict==='partial'?'Есть верные мысли, но не всё':'Стоит вернуться к материалу'}</strong><span>{assessment.score}%</span></div><p>{assessment.feedback}</p>{assessment.missing.length?<><h3>Что можно дополнить</h3><ul>{assessment.missing.map((item,i)=><li key={i}>{item}</li>)}</ul></>:null}{assessment.sourceQuote?<blockquote><span>Подтверждение в лекции</span>{assessment.sourceQuote}</blockquote>:null}<p className="assessment-note">ИИ сравнивает смысл с материалом и может ошибаться. Проверьте разбор по источнику.</p></div>:null}
   <div className="answer-box"><span className="eyebrow">РАЗБОР ПО ЛЕКЦИИ</span><p className="prose">{question.answer}</p>{question.sourceQuote?<blockquote><span>Фрагмент источника</span>{question.sourceQuote}</blockquote>:null}</div>
   {assessment?<div className="quiz-actions"><button className="button primary" disabled={busy} onClick={()=>next(assessment.verdict==='correct')}>Следующий вопрос <ArrowRight size={17}/></button></div>:<><p className="muted small">Как вы оцениваете свой ответ?</p><div className="quiz-actions"><button className="button" onClick={()=>next(false)}>Нужно повторить</button><button className="button primary" onClick={()=>next(true)}>Помню и понимаю <Check size={17}/></button></div></>}
  </>}
  <p className="quiz-quota-note">Проверка с ИИ использует один запуск из лимита. До {PILOT_LIMITS.assessmentsPerMaterial} сохранённых ИИ-проверок на лекцию. Ручная самопроверка доступна без ИИ.</p><button className="text-button quiz-exit" disabled={busy} onClick={exit}>Закончить без сохранения</button>
 </>}</section>;
}
