import {randomUUID,randomBytes} from 'node:crypto';
import {AppError,readJSON,writeObject} from '@/lib/storage';
import {checkOrigin,consumeLimit,rateKey,usernamePath,hashPassword,verifyPassword,hashRecovery,setSession,publicUser} from '@/lib/auth';
import {body,json,route} from '@/lib/http';
import type {User} from '@/lib/types';
export async function POST(request:Request){return route(async()=>{checkOrigin(request);if(!process.env.AUTH_SECRET||process.env.AUTH_SECRET.length<32)throw new AppError('Вход ещё не настроен.',503);const input=await body(request);const username=String(input.username||'').toLowerCase().trim();const password=String(input.password||'');if(!/^[a-z0-9_\-.]{3,40}$/.test(username))throw new AppError('Логин: 3–40 латинских букв, цифры, точка или подчёркивание.');if(password.length<10||password.length>128)throw new AppError('Пароль должен содержать от 10 до 128 символов.');await consumeLimit('auth:'+rateKey(request),15,15*60000);const path=usernamePath(username);const old=await readJSON<User>(path);
 if(input.action==='register'){await consumeLimit('register:'+rateKey(request),5,86400000);if(old)throw new AppError('Этот логин уже занят.',409);const recoveryCode=randomBytes(24).toString('hex');const user:User={id:randomUUID(),username,passwordHash:hashPassword(password),recoveryHash:hashRecovery(recoveryCode),createdAt:new Date().toISOString(),version:1};await writeObject(path,JSON.stringify(user),{createOnly:true});await setSession(user);return json({user:publicUser(user),recoveryCode},201)}
 if(input.action==='recover'){if(!old||hashRecovery(String(input.recoveryCode||''))!==old.value.recoveryHash)throw new AppError('Логин или код восстановления неверен.',403);const recoveryCode=randomBytes(24).toString('hex');const user={...old.value,passwordHash:hashPassword(password),recoveryHash:hashRecovery(recoveryCode),version:old.value.version+1};await writeObject(path,JSON.stringify(user),{etag:old.etag});await setSession(user);return json({user:publicUser(user),recoveryCode})}
 if(input.action!=='login'||!old||!verifyPassword(password,old.value.passwordHash)){verifyPassword(password,hashPassword('constant-dummy-password'));throw new AppError('Логин или пароль неверен.',403)}await setSession(old.value);return json({user:publicUser(old.value)})})}
