"use client";

import { useId, useRef, useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, Check, ChevronRight, FileText, GraduationCap, Plus, Search, Send, Sparkles, X } from "lucide-react";
import { BrandWordmark } from "@/components/brand/wordmark";
import { LegalFooter } from "@/components/legal/footer";
import { PLAN, PILOT_LIMITS } from "@/lib/plans";
import styles from "./polka-landing.module.css";

type DemoTab = "notes" | "concepts" | "practice" | "chat";
const demoTabs: { id: DemoTab; title: string; icon: typeof FileText }[] = [
  { id: "notes", title: "Конспект", icon: FileText },
  { id: "concepts", title: "Понятия", icon: BookOpen },
  { id: "practice", title: "Практика", icon: GraduationCap },
  { id: "chat", title: "polka.ai", icon: Sparkles },
];

function DemoWorkspace() {
  const id = useId();
  const [tab, setTab] = useState<DemoTab>("notes");
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [answer, setAnswer] = useState<number | null>(null);
  const [chatAsked, setChatAsked] = useState(false);
  const searchOpener = useRef<HTMLButtonElement | null>(null);
  function openSearch(button: HTMLButtonElement) { searchOpener.current = button; setSearchOpen(true); }
  function closeSearch() { setSearchOpen(false); searchOpener.current?.focus(); }
  function pickSearchResult(result: { tab: DemoTab }) { setTab(result.tab); setQuery(""); closeSearch(); }
  const searchItems = [{ title: "Как мы запоминаем", kind: "Лекция · Психология", keywords: "память", tab: "notes" as DemoTab }, { title: "Интервальное повторение", kind: "Понятие · из этой лекции", keywords: "память знания", tab: "concepts" as DemoTab }, { title: "Проверить понимание", kind: "Практика · один вопрос", keywords: "память повторение", tab: "practice" as DemoTab }];
  const results = searchItems.filter(item => `${item.title} ${item.kind} ${item.keywords}`.toLocaleLowerCase("ru").includes(query.toLocaleLowerCase("ru").trim()));

  return <div className={styles.demo} aria-label="Интерактивный пример полки">
    <div className={styles.demoToolbar}><div className={styles.windowDots} aria-hidden="true"><i /><i /><i /></div><span>ваша полка</span><span className={styles.demoBadge}>Демо</span></div>
    <div className={styles.demoBody}>
      <aside className={styles.demoSidebar} aria-label="Навигация примера"><BrandWordmark tone="light" className={styles.demoLogo} /><button className={styles.demoSearch} onClick={event => openSearch(event.currentTarget)} aria-expanded={searchOpen}><Search size={15} /><span>Найти на полке</span></button><div className={styles.demoNav}><span><FileText size={15} />Материалы</span><span><BookOpen size={15} />Знания</span><span><GraduationCap size={15} />Повторение</span></div><div className={styles.demoSubjects}><span>ПРЕДМЕТЫ</span><div><i />Психология <b>1</b></div><div><i />Мои заметки <b>0</b></div></div><div className={styles.demoProfile}><span>А</span><div>Артём<small>polka.id</small></div></div></aside>
      <div className={styles.demoContent}>
        <div className={styles.demoBreadcrumb}><span>Психология</span><ChevronRight size={13} /><span>Лекция 01</span><span className={styles.demoReady}><Check size={12} />Готово</span><button className={styles.demoMobileSearch} aria-label="Найти в примере полки" aria-expanded={searchOpen} onClick={event => openSearch(event.currentTarget)}><Search size={15} /></button></div>
        <div className={styles.demoTitle}><h3>Как мы запоминаем</h3><span>Одна лекция. Несколько способов разобраться.</span></div>
        <div className={styles.demoTabs} role="tablist" aria-label="Посмотреть возможности полки" onKeyDown={event => { const index = demoTabs.findIndex(item => item.id === tab); const next = event.key === "ArrowRight" ? (index + 1) % demoTabs.length : event.key === "ArrowLeft" ? (index + demoTabs.length - 1) % demoTabs.length : event.key === "Home" ? 0 : event.key === "End" ? demoTabs.length - 1 : -1; if (next >= 0) { event.preventDefault(); setTab(demoTabs[next].id); event.currentTarget.querySelectorAll<HTMLButtonElement>("button")[next]?.focus(); } }}>{demoTabs.map(item => <button key={item.id} id={`${id}-${item.id}-tab`} role="tab" tabIndex={tab === item.id ? 0 : -1} aria-selected={tab === item.id} aria-controls={`${id}-panel`} className={tab === item.id ? styles.selectedTab : ""} onClick={() => setTab(item.id)}><item.icon size={15} /><span>{item.title}</span></button>)}</div>
        <div className={styles.demoPage} id={`${id}-panel`} role="tabpanel" aria-labelledby={`${id}-${tab}-tab`}>
          {tab === "notes" && <div className={styles.noteColumns}><div className={styles.demoNote}><span className={styles.tinyLabel}>ГЛАВНОЕ ЗА МИНУТУ</span><h4>Память любит возвращения.</h4><p>Рабочая память удерживает информацию ненадолго. Чтобы запомнить надолго, полезно возвращаться к материалу через промежутки времени.</p><div className={styles.noteLine}><span>01</span><div><strong>Понять главное</strong><p>Выделить идею и объяснить её своими словами.</p></div></div><div className={styles.noteLine}><span>02</span><div><strong>Вернуться к материалу</strong><p>Распределить повторения во времени.</p></div></div></div><div className={styles.demoSource}><div><FileText size={15} /><span>Исходный материал</span></div><span className={styles.sourceSheetLabel}>ЛЕКЦИЯ 01 / ФРАГМЕНТ</span><p>«Интервальное повторение помогает возвращаться к материалу через промежутки времени».</p><div className={styles.paperLines} aria-hidden="true"><i /><i /><i /><i /></div><span className={styles.sourceCaption}><Check size={12} />Оригинал остаётся рядом</span></div></div>}
          {tab === "concepts" && <div className={styles.conceptsDemo}><span className={styles.tinyLabel}>ИЗ ЛЕКЦИИ — В ЗНАНИЯ</span><h4>Интервальное повторение</h4><p>Возвращение к материалу через промежутки времени, чтобы закрепить его в памяти.</p><blockquote>«Интервальное повторение помогает возвращаться к материалу через промежутки времени».</blockquote><span className={styles.demoSourceLink}><FileText size={14} />Как мы запоминаем · фрагмент лекции</span><div className={styles.demoConceptTags}><span>Память</span><span>Обучение</span><span>Повторение</span></div><small>Пример понятия. В вашей полке понятия можно сохранить после проверки.</small></div>}
          {tab === "practice" && <div className={styles.practiceDemo}><span className={styles.tinyLabel}>САМОПРОВЕРКА / 01</span><h4>Что помогает закрепить материал в памяти?</h4><div className={styles.demoAnswers}>{["Один раз быстро перечитать", "Возвращаться к нему через промежутки времени"].map((text, index) => <button key={text} aria-pressed={answer === index} className={answer === index ? styles.chosenAnswer : ""} onClick={() => setAnswer(index)}><span>{String.fromCharCode(65 + index)}</span>{text}{answer === index && <Check size={15} />}</button>)}</div>{answer !== null ? <p className={styles.demoFeedback} role="status">{answer === 1 ? "Верно. В этом фрагменте лекции описано интервальное повторение." : "Вернитесь к фрагменту: автор говорит о повторениях через промежутки времени."} <span>Источник: «Как мы запоминаем».</span></p> : <p className={styles.demoHint}>Выберите ответ — попробуйте, как устроена самопроверка.</p>}</div>}
          {tab === "chat" && <div className={styles.chatDemo}><div className={styles.chatDemoTitle}><Sparkles size={18} /><span>Разберёмся вместе.</span></div><p>Задавайте вопросы по материалам своей библиотеки.</p>{chatAsked ? <div className={styles.demoConversation}><div className={styles.demoUserMessage}>Как повторять эту лекцию?</div><div className={styles.demoAiMessage}><span>polka.ai</span><p>Сначала объясните главную идею своими словами. Затем вернитесь к материалу через промежуток времени и проверьте, что помните.</p><small><FileText size={12} />По примеру лекции «Как мы запоминаем»</small></div></div> : <button className={styles.demoQuestion} onClick={() => setChatAsked(true)}>Как повторять эту лекцию? <ArrowUpRight size={15} /></button>}<button className={styles.demoPrompt} onClick={() => setChatAsked(true)} aria-label="Показать пример ответа polka.ai"><Plus size={16} /><span>{chatAsked ? "Пример ответа показан выше" : "Спросить polka.ai"}</span><span className={styles.demoSend}><ArrowRight size={15} /></span></button></div>}
        </div>
        <div className={styles.demoFoot}><span><Sparkles size={12} />ИИ помогает. Источник подтверждает.</span><span>Демонстрационный материал</span></div>
      </div>
    </div>
    {searchOpen && <div className={styles.demoSearchOverlay} role="search" aria-label="Поиск по примеру полки" onKeyDown={event => { if (event.key === "Escape") closeSearch(); }}><div className={styles.demoSearchBox}><div><Search size={18} /><input autoFocus aria-label="Поиск по демонстрационной полке" value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && results[0]) { event.preventDefault(); pickSearchResult(results[0]); } }} placeholder="Найти лекцию, понятие, действие…" /><button aria-label="Закрыть поиск примера" onClick={closeSearch}><X size={18} /></button></div><span>В ЭТОМ ПРИМЕРЕ</span>{results.length ? results.map(item => <button key={item.title} onClick={() => pickSearchResult(item)}><FileText size={17} /><div><strong>{item.title}</strong><small>{item.kind}</small></div><ArrowUpRight size={15} /></button>) : <p role="status">В примере нет совпадений. Попробуйте «память» или «повторение».</p>}<small>Это демонстрация поиска. В аккаунте вы ищете по своим материалам.</small></div></div>}
  </div>;
}

export function PolkaLanding({ start, login, back, sessionError, retry, storageReady = true, preview = false }: { start: () => void; login?: () => void; back?: () => void; sessionError?: string; retry?: () => void; storageReady?: boolean; preview?: boolean }) {
  const prefix = useId().replaceAll(":", "");
  const how = `${prefix}-how`;
  const product = `${prefix}-product`;
  const price = `${prefix}-price`;
  return <div className={styles.site} data-polka-landing>
    <div className={styles.darkIntro}>
      <header className={styles.header}><a href="#" aria-label="polka — главная"><BrandWordmark tone="dark" className={styles.wordmark} /></a><nav aria-label="Разделы сайта"><a href={`#${product}`}>Возможности</a><a href={`#${how}`}>Как устроено</a><a href={`#${price}`}>Тариф</a></nav><div className={styles.headerActions}>{preview && back ? <button className={styles.loginButton} onClick={back}>К моей полке <ArrowUpRight size={15} /></button> : <button className={styles.loginButton} onClick={login ?? start}>Войти <ArrowUpRight size={15} /></button>}</div></header>
      <main>
        {sessionError && <div className={styles.notice} role="alert"><span>{sessionError}</span>{retry && <button onClick={retry}>Повторить</button>}</div>}
        {!storageReady && <div className={styles.notice}>Регистрация будет доступна, когда хранилище библиотеки будет готово.</div>}
        <section className={styles.hero} aria-labelledby={`${prefix}-title`}><div className={styles.heroLabel}><span className={styles.statusDot} />Личное пространство для учёбы<span className={styles.heroLabelRight}>МАТЕРИАЛ → ПОНИМАНИЕ</span></div><div className={styles.heroGrid}><h1 id={`${prefix}-title`}>Знания,<br />которые <em>остаются.</em><span className={styles.titleStar} aria-hidden="true">✦</span></h1><div className={styles.heroAside}><p>Всё, что вы учите,<br />обретает своё место.</p><span>Лекции, конспекты, понятия и вопросы.<br />С помощником, который знает контекст.</span><button className={styles.primaryButton} onClick={start} disabled={!storageReady && !preview}>{preview ? "Загрузить свой материал" : "Создать свою полку"}<ArrowUpRight size={19} /></button><a className={styles.demoAnchor} href={`#${product}`}><span>Посмотреть внутри</span><ArrowDown size={14} /></a></div></div></section>
        <section id={product} className={styles.productPreview} aria-labelledby={`${prefix}-preview-title`}><div className={styles.previewCaption}><h2 id={`${prefix}-preview-title`}>От одной лекции — к целой картине.</h2><span>НАЖМИТЕ НА ВКЛАДКИ И ПОПРОБУЙТЕ</span></div><DemoWorkspace /><div className={styles.formatRow}><span>НАЧНИТЕ С ТОГО, ЧТО У ВАС ЕСТЬ</span><div><span>PDF</span><i /><span>Текст</span><i /><span>Фото</span><i /><span>Аудио</span></div><span>На телефоне и компьютере <ArrowUpRight size={13} /></span></div></section>
      </main>
    </div>
    <section className={styles.howSection} id={how} aria-labelledby={`${prefix}-how-title`}><div className={styles.sectionIndex}><span>01 / КАК УСТРОЕНО</span><span>МЕНЬШЕ РУТИНЫ. БОЛЬШЕ СМЫСЛА.</span></div><div className={styles.sectionIntro}><h2 id={`${prefix}-how-title`}>Всё начинается<br />с <em>любопытства.</em></h2><p>polka собирает учебные материалы в одном месте. Помогает разобраться в них — и вернуться к знаниям, когда они понадобятся.</p></div><div className={styles.processRows}><article><span className={styles.processNumber}>01</span><h3>Принесите<br />материал.</h3><div><p>Файл, запись лекции или собственные заметки. Выберите предмет, чтобы собрать материалы вместе.</p><div className={styles.fileChip}><FileText size={17} /><span>Лекция_01.pdf<small>Исходный материал сохранён</small></span><Check size={16} /></div></div></article><article><span className={styles.processNumber}>02</span><h3>Разберите<br />главное.</h3><div><p>Получите конспект, понятия и вопросы. Уточните непонятное у polka.ai — с опорой на свою библиотеку.</p><div className={styles.textSample}><span>polka.ai</span>«Объясни эту идею проще» <ArrowUpRight size={15} /></div></div></article><article><span className={styles.processNumber}>03</span><h3>Сделайте знания<br />своими.</h3><div><p>Сохраните проверенные понятия. Объясните их своими словами и узнайте, что стоит повторить.</p><div className={styles.practiceMarks}><span><Check size={13} />Понял</span><span><BookOpen size={13} />Связал</span><span><GraduationCap size={13} />Повторил</span></div></div></article></div></section>
    <section className={styles.sourceSection} aria-labelledby={`${prefix}-source-title`}><div className={styles.sourceSectionCopy}><span className={styles.sectionLabel}>02 / НЕ ТЕРЯЙТЕ КОНТЕКСТ</span><h2 id={`${prefix}-source-title`}>У ответа<br />есть <em>источник.</em></h2><p>Оригинал всегда рядом с конспектом. В чате можно открыть материал, на который опирается помощник. Проверять — часть процесса.</p><span className={styles.aiNote}>ИИ может ошибаться. Важные выводы сверяйте с лекцией.</span></div><div className={styles.evidenceComposition}><div className={styles.evidenceQuestion}>Что такое интервальное повторение?</div><div className={styles.evidenceAnswer}><div><Sparkles size={17} /><span>polka.ai</span></div><p>Возвращение к материалу через промежутки времени, чтобы закрепить его в памяти.</p><span><FileText size={13} />Как мы запоминаем<ArrowUpRight size={13} /></span></div><div className={styles.evidenceSource}><span>ФРАГМЕНТ ИСХОДНОЙ ЛЕКЦИИ</span><p>«Интервальное повторение помогает возвращаться к материалу через промежутки времени».</p></div><span className={styles.evidenceCaption}>Демонстрация ответа и его источника</span></div></section>
    <section className={styles.planSection} id={price} aria-labelledby={`${prefix}-plan-title`}><div className={styles.sectionIndex}><span>03 / ВАША ПОЛКА</span><a href="/pricing">Все условия тарифа <ArrowUpRight size={14} /></a></div><div className={styles.planGrid}><div><h2 id={`${prefix}-plan-title`}>Место для того,<br />что <em>важно вам.</em></h2><p>Одна библиотека для лекций, идей и маленьких открытий. Открывайте её в браузере или добавьте на главный экран телефона.</p><span className={styles.deviceNote}>iPhone · Android · компьютер</span></div><div className={styles.planCard}><div className={styles.planTop}><span>polka / все возможности</span><ArrowUpRight size={18} /></div><div className={styles.planPrice}><strong>{PLAN.priceRub} <span>₽</span></strong><span>за {PLAN.periodDays} дней</span></div><div className={styles.planFeatures}><span><Check size={15} />{PILOT_LIMITS.materials} материалов и {PILOT_LIMITS.storageBytes / 1024 / 1024} МБ файлов</span><span><Check size={15} />{PLAN.aiPeriod} запусков ИИ за период</span><span><Check size={15} />Конспекты, понятия, чат и повторение</span></div><a className={styles.planButton} href="/pricing">Посмотреть тариф <ArrowRight size={17} /></a><small>Продление вручную. Без автоматических списаний.<br />Доступность оплаты — на странице тарифа.</small></div></div></section>
    <section className={styles.telegramSection}><div><span className={styles.sectionLabel}>ПРОДОЛЖИМ В TELEGRAM</span><h2>Учёба сегодня.<br />Карьера <em>завтра.</em></h2></div><div><p>Канал polka об учёбе и карьере.</p><a href="https://t.me/polka_it" target="_blank" rel="noopener noreferrer">@polka_it <Send size={18} /><ArrowUpRight size={18} /></a></div></section>
    <section className={styles.finalSection}><div><span className={styles.sectionLabel}>СЛЕДУЮЩАЯ ИДЕЯ — ВАША</span><h2>Откройте свою полку.</h2></div><button className={styles.primaryButton} onClick={start} disabled={!storageReady && !preview}>{preview ? "Вернуться к учёбе" : "Начать"}<ArrowUpRight size={19} /></button></section>
    <div className={styles.footerWrap}><LegalFooter /></div>
  </div>;
}
