'use client';
import {useEffect,useState,useCallback} from 'react';
import Link from 'next/link';
import {LayoutDashboard,Users,Database,Activity,CreditCard,RefreshCw,Search,ArrowLeft,ArrowUpRight,Download,CheckCircle2,AlertTriangle,FileText,MessageSquare,ShieldCheck,X} from 'lucide-react';
import type {OwnerOverview,OwnerDetail,OwnerContent,OwnerHealth,OwnerStorage,HealthStatus} from '@/lib/admin-types';
import type {BillingOrder} from '@/lib/billing';

type Tab='overview'|'users'|'storage'|'health'|'billing';
const tabs:{id:Tab;title:string;icon:typeof Users}[]=[{id:'overview',title:'Обзор',icon:LayoutDashboard},{id:'users',title:'Пользователи',icon:Users},{id:'billing',title:'Платежи',icon:CreditCard},{id:'storage',title:'Хранилище',icon:Database},{id:'health',title:'Состояние',icon:Activity}];
const number=(value:number)=>value.toLocaleString('ru-RU');
const bytes=(value:number)=>value>=1024**3?`${(value/1024**3).toFixed(2)} ГБ`:value>=1024**2?`${(value/1024**2).toFixed(1)} МБ`:value>=1024?`${(value/1024).toFixed(1)} КБ`:`${value} Б`;
const date=(value:string|null,short=false)=>value?new Date(value).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'numeric',month:'short',...(short?{}:{hour:'2-digit',minute:'2-digit'})}):'—';
const money=(value:number|string)=>Number(value).toLocaleString('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:2});
const kindName:Record<string,string>={text:'Текст',pdf:'PDF',audio:'Аудио',image:'Изображения',video:'Видео'};
const orderStatus:Record<string,string>={created:'Создан',pending:'Ожидает оплаты',succeeded:'Оплачен',canceled:'Отменён',refunded:'Возвращён'};
async function api<T>(path:string,options?:RequestInit):Promise<T>{const response=await fetch('/api/admin/'+path,{cache:'no-store',...options});const data=await response.json();if(!response.ok)throw new Error(data.error||'Не удалось загрузить данные.');return data}
function download(data:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
function Empty({children}:{children:React.ReactNode}){return <p className="owner-empty">{children}</p>}
function Badge({status,children}:{status:HealthStatus|'neutral';children:React.ReactNode}){return <span className={`owner-badge ${status}`}>{children}</span>}

export default function OwnerConsole(){
 const [tab,setTab]=useState<Tab>('overview');const [overview,setOverview]=useState<OwnerOverview>();const [detail,setDetail]=useState<OwnerDetail>();const [content,setContent]=useState<OwnerContent>();const [health,setHealth]=useState<OwnerHealth>();const [storage,setStorage]=useState<OwnerStorage>();const [billing,setBilling]=useState<{orders:BillingOrder[];complete:boolean;updatedAt:string}>();const [search,setSearch]=useState('');const [prefix,setPrefix]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [receipt,setReceipt]=useState<BillingOrder>();
 const load=useCallback(async()=>{setBusy(true);setError('');try{if(tab==='overview'||tab==='users')setOverview(await api<OwnerOverview>('overview'));else if(tab==='health')setHealth(await api<OwnerHealth>('health'));else if(tab==='billing')setBilling(await api('billing'));else setStorage(await api<OwnerStorage>('storage?prefix='+encodeURIComponent(prefix)))}catch(error){setError(error instanceof Error?error.message:'Не удалось загрузить панель.')}finally{setBusy(false)}},[tab,prefix]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!content&&!receipt)return;const previous=document.activeElement as HTMLElement|null;const modal=document.querySelector<HTMLElement>('.owner-modal');const controls=()=>Array.from(modal?.querySelectorAll<HTMLElement>('button,a[href],input,select,textarea,[tabindex="0"]')||[]).filter(item=>!item.hasAttribute('disabled'));controls()[0]?.focus();const keyboard=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy){setContent(undefined);setReceipt(undefined)}if(event.key==='Tab'){const items=controls();const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}};document.addEventListener('keydown',keyboard);return()=>{document.removeEventListener('keydown',keyboard);previous?.focus()}},[content,receipt,busy]);
 async function openUser(id:string){setBusy(true);setError('');setContent(undefined);try{setDetail(await api<OwnerDetail>('users/'+id));setTab('users')}catch(error){setError((error as Error).message)}finally{setBusy(false)}}
 async function openContent(kind:'material'|'chat',id:string){if(!detail)return;setBusy(true);setError('');try{setContent(await api<OwnerContent>(`users/${detail.user.id}/${kind}/${id}`))}catch(error){setError((error as Error).message)}finally{setBusy(false)}}
 async function checkHealth(){setBusy(true);setError('');try{setHealth(await api<OwnerHealth>('health',{method:'POST'}))}catch(error){setError((error as Error).message)}finally{setBusy(false)}}
 async function markReceipt(){if(!receipt)return;setBusy(true);setError('');try{await api('receipts/'+receipt.id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true})});setReceipt(undefined);setBilling(await api('billing'))}catch(error){setError((error as Error).message)}finally{setBusy(false)}}
 const filtered=overview?.users.filter(user=>`${user.username} ${user.id}`.toLowerCase().includes(search.toLowerCase().trim()))||[];
 const totals=overview?.totals;
 function chooseTab(value:Tab){setTab(value);setDetail(undefined);setContent(undefined);setSearch('')}
 return <div className="owner-shell"><aside className="owner-sidebar"><Link href="/" className="owner-brand"><span className="owner-mark">П</span><span>Полка<small>Панель владельца</small></span></Link><nav aria-label="Разделы панели">{tabs.map(item=><button key={item.id} className={tab===item.id?'active':''} onClick={()=>chooseTab(item.id)}><item.icon size={18}/><span>{item.title}</span></button>)}</nav><div className="owner-sidebar-bottom"><ShieldCheck size={17}/><span>Закрытый доступ</span><Link href="/">Открыть приложение <ArrowUpRight size={15}/></Link></div></aside>
 <main className="owner-main"><header className="owner-header"><div><p className="owner-eyebrow">Рабочее пространство владельца</p><h1>{tabs.find(item=>item.id===tab)?.title}</h1></div><div className="owner-header-actions"><span className="owner-caption">{date(overview?.updatedAt||null)} · МСК</span><button className="owner-button" onClick={()=>void load()} disabled={busy}><RefreshCw size={16} className={busy?'owner-spin':''}/><span>Обновить</span></button></div></header>
 {error&&<div role="alert" className="owner-alert"><AlertTriangle size={18}/>{error}</div>}{busy&&<div role="status" className="owner-loading">Обновляю данные…</div>}
 {tab==='overview'&&overview&&<><div className="owner-intro"><div><h2>Сервис одним взглядом</h2><p>Фактические данные аккаунтов и учебных библиотек.</p></div><button className="owner-button" onClick={()=>chooseTab('health')}>Проверить работу <ArrowUpRight size={15}/></button></div>{overview.warnings.map(warning=><div key={warning} className="owner-alert">{warning}</div>)}<div className="owner-kpis">{[{label:'Пользователи',value:number(totals!.users),note:'Зарегистрированные аккаунты',icon:Users},{label:'Материалы',value:number(totals!.materials),note:`${number(totals!.ready)} подготовлено · ${number(totals!.materials-totals!.ready)} во входящих`,icon:FileText},{label:'Запуски ИИ сегодня',value:number(totals!.aiToday),note:'С начала суток UTC; включая попытки',icon:Activity},{label:'Файлы пользователей',value:bytes(totals!.fileBytes),note:`${bytes(totals!.reservedBytes)} зарезервировано загрузками`,icon:Database}].map(item=><section className="owner-kpi" key={item.label}><div><span>{item.label}</span><item.icon size={17}/></div><strong>{item.value}</strong><small>{item.note}</small></section>)}</div>
 <div className="owner-grid"><section className="owner-card"><header><h2>Новые аккаунты</h2><span>7 дней · UTC</span></header><div className="owner-bars" role="img" aria-label={overview.registrations.map(item=>`${item.day}: ${item.count} аккаунтов`).join('; ')}>{overview.registrations.map(item=><div className="owner-bar-column" key={item.day}><strong>{item.count}</strong><div><i style={{height:item.count?`${Math.max(5,item.count/Math.max(1,...overview.registrations.map(day=>day.count))*100)}%`:'2px'}}/></div><span>{date(item.day,true)}</span></div>)}</div></section><section className="owner-card"><header><h2>Учебная база</h2></header><div className="owner-breakdown"><div><span>Понятия</span><strong>{number(totals!.topics)}</strong></div><div><span>Сохранённые чаты</span><strong>{number(totals!.chats)}</strong></div><div><span>Попытки повторения</span><strong>{number(totals!.reviews)}</strong></div></div><h3>Материалы по формату</h3>{overview.kinds.length?overview.kinds.map(item=><div className="owner-kind" key={item.kind}><span>{kindName[item.kind]}</span><div><i style={{width:`${item.count/Math.max(1,totals!.materials)*100}%`}}/></div><strong>{item.count}</strong></div>):<Empty>Материалов пока нет</Empty>}</section></div>
 <section className="owner-card"><header><h2>Последние регистрации</h2><button onClick={()=>chooseTab('users')} className="owner-link">Все пользователи <ArrowUpRight size={15}/></button></header><UserTable users={overview.users.slice(0,5)} onOpen={openUser}/></section><p className="owner-caption">Изменение контента показывает дату последнего сохранения материала, понятия или чата. Истории посещений и сквозной аналитики пока нет.</p></>}
 {tab==='users'&&!detail&&<section className="owner-card"><header><h2>Аккаунты <span className="owner-count">{filtered.length}</span></h2><label className="owner-search"><Search size={17}/><input aria-label="Найти пользователя" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Логин или ID"/></label></header><UserTable users={filtered} onOpen={openUser}/></section>}
 {tab==='users'&&detail&&<><button className="owner-back" onClick={()=>{setDetail(undefined);setContent(undefined)}}><ArrowLeft size={16}/>Все пользователи</button><section className="owner-card"><header><div><h2>{detail.user.username}</h2><p className="owner-caption">{detail.user.id} · регистрация {date(detail.user.createdAt)}</p></div><a className="owner-button" href={`/api/admin/users/${detail.user.id}/export`}><Download size={16}/>JSON библиотеки</a></header><div className="owner-detail-stats"><span><strong>{detail.user.materials}</strong> материалов</span><span><strong>{detail.user.topics}</strong> понятий</span><span><strong>{detail.user.chats}</strong> чатов</span><span><strong>{bytes(detail.user.fileBytes)}</strong> файлов</span><span><strong>{detail.user.aiToday}</strong> запусков ИИ сегодня</span></div></section><div className="owner-grid"><section className="owner-card"><header><h2>Лекции и материалы</h2></header>{detail.library.materials.length?<div className="owner-records">{detail.library.materials.map(material=><button key={material.id} onClick={()=>void openContent('material',material.id)}><FileText size={18}/><span><strong>{material.title}</strong><small>{kindName[material.kind]} · {date(material.updatedAt)} · {material.status==='ready'?'Подготовлено':'Входящие'}</small></span><ArrowUpRight size={16}/></button>)}</div>:<Empty>Материалов нет</Empty>}</section><section className="owner-card"><header><h2>Чаты помощника</h2></header>{detail.library.chats?.length?<div className="owner-records">{detail.library.chats.map(chat=><button key={chat.id} onClick={()=>void openContent('chat',chat.id)}><MessageSquare size={18}/><span><strong>{chat.title}</strong><small>{date(chat.updatedAt)}</small></span><ArrowUpRight size={16}/></button>)}</div>:<Empty>Чатов нет</Empty>}</section></div><section className="owner-card"><header><h2>База знаний</h2><span>{detail.library.topics.length} понятий</span></header>{detail.library.topics.length?<div className="owner-topics">{detail.library.topics.map(topic=><details key={topic.id}><summary>{topic.title}</summary><p>{topic.body}</p>{topic.sourceQuote&&<blockquote>{topic.sourceQuote}</blockquote>}</details>)}</div>:<Empty>Понятий пока нет</Empty>}</section></>}
 {tab==='storage'&&storage&&<section className="owner-card"><header><div><h2>Объекты хранилища</h2><p className="owner-caption">Текущая страница: {storage.objects.length} объектов · {bytes(storage.pageBytes)}. Содержимое служебных записей скрыто.</p></div><select aria-label="Раздел хранилища" value={prefix} onChange={event=>setPrefix(event.target.value)}>{[['','Все разделы'],['users/','Библиотеки и файлы'],['accounts/','Аккаунты'],['billing/','Платежи'],['operations/','Работа сервиса'],['limits/','Лимиты запросов']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></header><div className="owner-table-wrap"><table><thead><tr><th>Объект</th><th>Размер</th><th>Обновление · МСК</th></tr></thead><tbody>{storage.objects.map(object=><tr key={object.pathname}><td className="owner-path">{object.pathname}</td><td>{bytes(object.size)}</td><td>{date(object.uploadedAt)}</td></tr>)}</tbody></table></div>{!storage.objects.length&&<Empty>В разделе пока нет объектов</Empty>}{storage.hasMore&&<button className="owner-button" disabled={busy} onClick={async()=>{setBusy(true);try{setStorage(await api(`storage?prefix=${encodeURIComponent(prefix)}&cursor=${encodeURIComponent(storage.cursor||'')}`))}catch(error){setError((error as Error).message)}finally{setBusy(false)}}}>Следующие 100 объектов</button>}</section>}
 {tab==='health'&&health&&<><section className="owner-card"><header><div><h2>Подключения и доступность</h2><p className="owner-caption">{date(health.checkedAt)} · МСК</p></div><button className="owner-primary" disabled={busy} onClick={()=>void checkHealth()}><Activity size={16}/>Проверить соединения</button></header><div className="owner-checks">{health.checks.map(check=><article key={check.name}><div>{check.status==='ok'?<CheckCircle2 size={20}/>:<AlertTriangle size={20}/>}<strong>{check.name}</strong><Badge status={check.status}>{({ok:'Доступно',warning:'Требует проверки',error:'Ошибка',unconfigured:'Не настроено'})[check.status]}</Badge></div><p>{check.detail}</p>{check.latencyMs!==undefined&&<small>{check.latencyMs} мс</small>}</article>)}</div><p className="owner-caption">Проверка читает хранилище и проверяет ключи провайдеров. Она не создаёт платежи и не запускает платную генерацию. Это разовая проверка, а не показатель непрерывной доступности.</p></section><section className="owner-card"><header><h2>История проверок</h2><span>Последние 20 запусков</span></header>{health.history.length?<div className="owner-table-wrap"><table><thead><tr><th>Когда · МСК</th><th>Успешно</th><th>Требует внимания</th></tr></thead><tbody>{health.history.map(item=><tr key={item.checkedAt}><td>{date(item.checkedAt)}</td><td>{item.ok}</td><td>{item.issues}</td></tr>)}</tbody></table></div>:<Empty>Запустите первую проверку</Empty>}</section></>}
 {tab==='billing'&&billing&&<><div className="owner-kpis">{[{label:'Оплаченные заказы',value:number(billing.orders.filter(order=>!order.test&&order.status==='succeeded').length),note:'Без тестов и полных возвратов'},{label:'Поступления после возвратов',value:money(billing.orders.filter(order=>!order.test&&['succeeded','refunded'].includes(order.status)).reduce((sum,order)=>sum+Number(order.amount)-Math.min(Number(order.amount),Math.max(order.canonicalRefundedRub||0,(order.refunds||[]).reduce((n,refund)=>n+Number(refund.amount),0))),0)),note:'До комиссии ЮKassa и налога'},{label:'Чеки к отправке',value:number(billing.orders.filter(order=>!order.test&&order.status==='succeeded'&&!order.receiptSentAt).length),note:'Сформировать вручную в «Мой налог»'}].map(item=><section className="owner-kpi" key={item.label}><span>{item.label}</span><strong>{item.value}</strong><small>{item.note}</small></section>)}</div>{!billing.complete&&<div className="owner-alert">Показаны первые 1000 заказов. Итоги неполные.</div>}<section className="owner-card"><header><h2>Заказы</h2><span>Обновлено {date(billing.updatedAt)}</span></header><p className="owner-caption">Чек самозанятого формируется в «Мой налог» и отправляется покупателю вручную. Кнопка ниже фиксирует уже отправленный чек.</p>{billing.orders.length?<div className="owner-table-wrap"><table><thead><tr><th>Покупатель / заказ</th><th>Сумма</th><th>Статус</th><th>Чек</th></tr></thead><tbody>{billing.orders.map(order=><tr key={order.id}><td><strong>{order.username}</strong><small>{order.contactEmail}</small><small className="owner-path">{order.id}</small><small>{date(order.createdAt)}</small></td><td>{money(order.amount)}{order.test&&<Badge status="neutral">Тест</Badge>}</td><td><Badge status={order.status==='succeeded'?'ok':order.status==='canceled'?'error':'neutral'}>{orderStatus[order.status]}</Badge></td><td>{order.receiptSentAt?date(order.receiptSentAt):order.status==='succeeded'&&!order.test?<button className="owner-button" onClick={()=>setReceipt(order)}>Чек отправлен</button>:'—'}</td></tr>)}</tbody></table></div>:<Empty>Заказов пока нет. Здесь появятся реальные платежи после подключения ЮKassa.</Empty>}</section></>}
 </main>
 {content&&<div className="owner-modal-backdrop" onClick={()=>setContent(undefined)}><section className="owner-modal" role="dialog" aria-modal="true" aria-label="Содержимое записи" onClick={event=>event.stopPropagation()}><header><div><h2>{content.content.title}</h2><span className="owner-caption">{content.kind==='material'?'Материал':'Чат'} · {content.content.id}</span></div><button aria-label="Закрыть запись" className="owner-icon-button" onClick={()=>setContent(undefined)}><X size={20}/></button></header><div className="owner-modal-body">{content.kind==='material'?<><h3>Оригинальный текст</h3><p className="owner-source">{content.content.text||'Текст ещё не извлечён'}</p><h3>Конспект</h3><p className="owner-source">{content.content.summary||'Конспект ещё не создан'}</p>{content.content.warning&&<div className="owner-alert">{content.content.warning}</div>}</>:<><Badge status={content.content.status==='failed'?'error':'neutral'}>{content.content.status==='failed'?'Ошибка':content.content.status==='streaming'?'Готовится ответ':'Сохранён'}</Badge>{content.content.error&&<div className="owner-alert">{content.content.error}</div>}{content.content.messages.map(message=><article className={`owner-message ${message.role}`} key={message.id}><small>{message.role==='user'?'Пользователь':'Помощник'} · {date(message.createdAt)}</small><p>{message.content}</p></article>)}</>}<details className="owner-json"><summary>Полная запись JSON</summary><pre>{JSON.stringify(content.content,null,2)}</pre></details></div><footer><button className="owner-button" onClick={()=>download(content.content,`polka-${content.kind}-${content.content.id}.json`)}><Download size={16}/>Скачать JSON</button><button className="owner-primary" onClick={()=>setContent(undefined)}>Готово</button></footer></section></div>}
 {receipt&&<div className="owner-modal-backdrop"><section className="owner-modal owner-confirm" role="dialog" aria-modal="true" aria-label="Подтверждение отправленного чека"><header><h2>Чек уже отправлен?</h2></header><p>Заказ {receipt.id}, {money(receipt.amount)}. Подтвердите, что сформировали чек в «Мой налог» и отправили его на {receipt.contactEmail}.</p><p className="owner-caption">Это только отметка в панели. Она не формирует и не отправляет чек.</p><footer><button className="owner-button" disabled={busy} onClick={()=>setReceipt(undefined)}>Отмена</button><button className="owner-primary" disabled={busy} onClick={()=>void markReceipt()}>Да, чек отправлен</button></footer></section></div>}
 </div>;
}
function UserTable({users,onOpen}:{users:OwnerOverview['users'];onOpen:(id:string)=>Promise<void>}){if(!users.length)return <Empty>Пользователей не найдено</Empty>;return <div className="owner-table-wrap"><table><thead><tr><th>Пользователь</th><th>Материалы</th><th>Понятия</th><th>Изменение контента · МСК</th><th/></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><button className="owner-user-link" onClick={()=>void onOpen(user.id)}>{user.username}</button><small>{date(user.createdAt)}</small></td><td>{user.materials}</td><td>{user.topics}</td><td>{date(user.lastContentAt)}</td><td><button className="owner-icon-button" aria-label={`Открыть ${user.username}`} onClick={()=>void onOpen(user.id)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>}
