"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowRight, BookOpen, Command, FileText, FolderOpen, GraduationCap, LayoutGrid, Library, MessageCircle, Plus, Search, Sparkles, UserRound, X } from "lucide-react";
import type { MaterialCard, Topic } from "@/lib/types";

export type WorkspacePage = "home" | "materials" | "subjects" | "knowledge" | "review" | "assistant" | "account";
const sections = [
  { id: "home", label: "Обзор", icon: LayoutGrid },
  { id: "materials", label: "Материалы", icon: Library },
  { id: "subjects", label: "Предметы", icon: FolderOpen },
  { id: "knowledge", label: "Знания", icon: BookOpen },
  { id: "review", label: "Практика", icon: GraduationCap },
  { id: "assistant", label: "polka.ai", icon: MessageCircle },
] as const;

export function VersionSwitch({ version, change }: { version: "v1" | "v2"; change: (version: "v1" | "v2") => void }) {
  return <div className="design-version-switch" role="group" aria-label="Версия интерфейса">
    <button type="button" aria-pressed={version === "v1"} onClick={() => change("v1")}><span className="version-long">Классический</span><span className="version-short">1.0</span></button>
    <button type="button" aria-pressed={version === "v2"} onClick={() => change("v2")}>2.0 <span className="version-beta">beta</span></button>
  </div>;
}

export function WorkspaceHeader({ page, username, navigate, search, changeVersion, previewSite }: { page: WorkspacePage; username: string; navigate: (page: WorkspacePage) => void; search: () => void; changeVersion: (version: "v1" | "v2") => void; previewSite: () => void }) {
  return <header className="v2-header"><div className="v2-header-main">
    <button className="v2-wordmark" onClick={() => navigate("home")} aria-label="Полка — обзор"><span className="v2-logo-mark" aria-hidden="true"><i /><i /><i /></span>полка<span className="v2-wordmark-version">/ 2.0</span></button>
    <div className="v2-header-actions"><button className="v2-search-trigger" onClick={search} aria-label="Открыть поиск и команды"><Search size={16} /><span>Поиск</span><kbd>⌘ K</kbd></button><VersionSwitch version="v2" change={changeVersion} /><button className="v2-profile-trigger" onClick={() => navigate("account")} aria-label="Открыть polka.id"><span>{username.slice(0, 1).toUpperCase()}</span><span className="v2-profile-label">polka.id</span></button></div>
  </div><div className="v2-header-bottom"><nav aria-label="Основная навигация 2.0">{sections.map(item => <button key={item.id} aria-current={page === item.id ? "page" : undefined} onClick={() => navigate(item.id)}><item.icon size={16} />{item.label}{item.id === "assistant" ? <span className="v2-ai-dot" /> : null}</button>)}</nav><button className="v2-site-link" onClick={previewSite}>О Полке <ArrowRight size={14} /></button></div></header>;
}

const dateLabel = (value: string) => new Intl.DateTimeFormat("ru", { day: "numeric", month: "short" }).format(new Date(value));
const formatLabel = { text: "Текст", pdf: "PDF", image: "Фото", audio: "Аудио", video: "Видео" };
type DashboardProps = { username: string; materials: MaterialCard[]; topics: number; reviews: number; loading: boolean; add: () => void; open: (id: string) => void; navigate: (page: WorkspacePage) => void; review: (id: string) => void; search: () => void; subject: (name: string) => void };

export function WorkspaceDashboard({ username, materials, topics, reviews, loading, add, open, navigate, review, search, subject }: DashboardProps) {
  const ready = materials.filter(item => item.status === "ready");
  const inbox = materials.filter(item => item.status === "inbox");
  const current = ready[0] || materials[0];
  const subjects = Array.from(new Set(materials.map(item => item.subject || "Без предмета")));
  return <div className="v2-dashboard">
    <section className="v2-overview-hero"><div className="v2-hero-copy"><span className="v2-eyebrow">ВАШЕ ПРОСТРАНСТВО / {username}</span><h1>Меньше рутины.<br /><span>Больше понимания.</span></h1><p>Материалы, идеи и вопросы — всё, чтобы учиться в своём ритме.</p><div className="v2-hero-actions"><button className="button primary" onClick={add}><Plus size={17} />Добавить материал</button><button className="button" onClick={() => navigate("assistant")}><Sparkles size={16} />Поговорить с polka.ai</button></div></div><div className="v2-hero-art" aria-hidden="true"><div className="v2-art-ring" /><div className="v2-art-bar" /><div className="v2-art-core"><BookOpen size={32} strokeWidth={1.2} /></div><span className="v2-art-caption">сохранить → понять → вспомнить</span></div></section>
    <button className="v2-command-entry" onClick={search}><Search size={19} /><span>Найти материал, понятие или открыть раздел</span><kbd><Command size={12} /> K</kbd><ArrowRight size={17} /></button>
    <section className="v2-stats" aria-label="Ваша библиотека">{[{ label: "Материалы", count: materials.length, page: "materials" }, { label: "Конспекты", count: ready.length, page: "materials" }, { label: "Понятия", count: topics, page: "knowledge" }, { label: "Повторения", count: reviews, page: "review" }].map(item => <button key={item.label} onClick={() => navigate(item.page as WorkspacePage)}><strong>{item.count.toString().padStart(2, "0")}</strong><span>{item.label}</span><ArrowRight size={14} /></button>)}</section>
    <div className="v2-focus-grid"><section className="v2-key-card v2-continue"><div className="v2-card-label"><span>ПРОДОЛЖИТЬ ИЗУЧЕНИЕ</span><BookOpen size={17} /></div>{current ? <><span className="v2-material-meta">{current.subject || "Без предмета"} <span>·</span> {formatLabel[current.kind]}</span><h2>{current.title}</h2><p>{current.excerpt || "Материал сохранён. Откройте его, чтобы подготовить конспект и разобраться в главном."}</p><div className="v2-card-actions"><button className="button primary" onClick={() => open(current.id)}>Открыть материал <ArrowRight size={16} /></button>{current.status === "ready" ? <button className="button" onClick={() => review(current.id)}><GraduationCap size={16} />Проверить себя</button> : null}</div></> : <><h2>Всё начинается<br />с первого материала.</h2><p>Лекция, PDF, запись или ваша заметка. Сохраните источник, а к разбору вернитесь, когда удобно.</p><button className="button primary" onClick={add}><Plus size={16} />Добавить первый материал</button></>}</section>
    <section className="v2-key-card v2-ai-card"><div className="v2-card-label"><span className="v2-ai-badge"><Sparkles size={13} />polka.ai</span><span>ВАШ УЧЕБНЫЙ ИИ</span></div><h2>Сложная тема?<br />Начнём с вопроса.</h2><p>Разберите идею, найдите пример или проверьте понимание. Ссылки на ваши материалы — рядом с ответом.</p><button className="v2-ai-prompt-entry" onClick={() => navigate("assistant")}><span>Спросить polka.ai</span><ArrowRight size={17} /></button><small>Ответы ИИ проверяйте по оригиналу.</small></section></div>
    <div className="v2-section-head"><div><span className="v2-eyebrow">ВСЁ НА СВОИХ МЕСТАХ</span><h2>Ваша библиотека</h2></div><button className="v2-text-action" onClick={() => navigate("materials")}>Все материалы <ArrowRight size={16} /></button></div>
    <div className="v2-library-grid"><section className="v2-key-card v2-recent">{loading && !materials.length ? <p role="status">Загружаем библиотеку…</p> : materials.length ? materials.slice(0, 4).map(item => <button className="v2-material-row" key={item.id} onClick={() => open(item.id)}><span className="v2-file-icon"><FileText size={19} /></span><span><strong>{item.title}</strong><small>{item.subject || "Без предмета"} · {dateLabel(item.createdAt)}</small></span><span className={`v2-row-status ${item.status === "ready" ? "is-ready" : ""}`}>{item.status === "ready" ? "Готово" : "Входящие"}</span><ArrowRight size={16} /></button>) : <div className="v2-list-empty"><Library size={24} /><h3>Здесь будут ваши материалы</h3><p>Ваша личная библиотека, без лишних папок.</p><button className="v2-text-action" onClick={add}>Добавить материал <Plus size={16} /></button></div>}</section><section className="v2-key-card v2-subjects"><div className="v2-card-label"><span>ПРЕДМЕТЫ</span><FolderOpen size={17} /></div>{subjects.length ? <div className="v2-subject-list">{subjects.slice(0, 4).map(name => <button key={name} onClick={() => subject(name)}><span>{name}</span><small>{materials.filter(item => (item.subject || "Без предмета") === name).length}</small><ArrowRight size={14} /></button>)}</div> : <p>Укажите предмет при загрузке — материалы соберутся вместе.</p>}<button className="v2-text-action" onClick={() => navigate("subjects")}>Открыть предметы <ArrowRight size={15} /></button></section></div>
    {inbox.length ? <button className="v2-inbox-strip" onClick={() => navigate("materials")}><span><span className="v2-inbox-dot" />На очереди: {inbox.length} материалов</span><span>Продолжить разбор <ArrowRight size={16} /></span></button> : null}
  </div>;
}

export function DesignLanding({ back, add }: { back: () => void; add: () => void }) {
  return <div className="v2-landing"><section className="v2-marketing-hero"><span className="v2-eyebrow">ЛИЧНАЯ БИБЛИОТЕКА С ИСКУССТВЕННЫМ ИНТЕЛЛЕКТОМ</span><h1>Оставьте знания.<br /><span>Отпустите рутину.</span></h1><p>Превращайте лекции и заметки в понимание.<br />Сохраняйте источники. Связывайте идеи. Проверяйте себя.</p><div className="v2-hero-actions"><button className="button primary" onClick={add}><Plus size={17} />Добавить материал</button><button className="button" onClick={back}>В мою библиотеку <ArrowRight size={16} /></button></div><div className="v2-marketing-art" aria-hidden="true"><i /><i /><i /><div className="v2-marketing-command"><Sparkles size={18} /><span>Один вопрос. Новое понимание.</span><kbd>↵</kbd></div></div><a href="#v2-how" className="v2-scroll-hint">Посмотреть, как устроено <ArrowDown size={15} /></a></section><section id="v2-how" className="v2-marketing-section"><span className="v2-eyebrow">СОХРАНИТЬ / ПОНЯТЬ / ВСПОМНИТЬ</span><h2>Ваш путь от материала<br />к собственным знаниям.</h2><div className="v2-feature-grid">{[{icon:Library,title:"Соберите на полке",body:"PDF, фото, аудио и тексты в личной библиотеке. Оригинал остаётся доступен рядом с конспектом."},{icon:Sparkles,title:"Разберитесь с polka.ai",body:"Краткое содержание, понятия и разговор по лекции. Проверяйте выводы помощника по своему источнику."},{icon:GraduationCap,title:"Проверьте понимание",body:"Отвечайте своими словами. Получайте разбор и фрагмент лекции, на который опирается ответ."}].map((item,index)=><article className="v2-key-card" key={item.title}><span className="v2-feature-number">0{index+1}</span><item.icon size={25} strokeWidth={1.4}/><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section><section className="v2-marketing-final"><BookOpen size={30} strokeWidth={1.2}/><h2>Первый материал.<br />Первое открытие.</h2><p>Учитесь на компьютере, в браузере телефона или в установленной Полке.</p><button className="button primary" onClick={back}>Открыть свою полку <ArrowRight size={16}/></button></section></div>;
}

export function CommandPalette({ materials, topics, navigate, open, add, close, previewSite }: { materials: MaterialCard[]; topics: Topic[]; navigate: (page: WorkspacePage) => void; open: (id: string) => void; add: () => void; close: () => void; previewSite: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  const input = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState("");
  const [active, setActive] = useState(0);
  useEffect(() => { const node = ref.current; node?.showModal(); input.current?.focus(); return () => node?.close(); }, []);
  const q = query.trim().toLocaleLowerCase("ru");
  const commands = [{ title: "Добавить материал", label: "Действие", icon: Plus, run: add }, ...sections.map(item => ({ title: item.label, label: "Раздел", icon: item.icon, run: () => navigate(item.id) })), { title: "polka.id · Аккаунт", label: "Раздел", icon: UserRound, run: () => navigate("account") }, { title: "О Полке · новый лендинг", label: "Предпросмотр", icon: LayoutGrid, run: previewSite }];
  const rows = [...commands.filter(item => item.title.toLocaleLowerCase("ru").includes(q)), ...materials.filter(item => `${item.title} ${item.subject}`.toLocaleLowerCase("ru").includes(q)).map(item => ({ title: item.title, label: item.subject || "Материал", icon: FileText, run: () => open(item.id) })), ...topics.filter(item => `${item.title} ${item.body}`.toLocaleLowerCase("ru").includes(q)).map(item => ({ title: item.title, label: "Понятие · открыть источник", icon: BookOpen, run: () => open(item.materialId) }))].slice(0, 10);
  const selected = Math.min(active, Math.max(0, rows.length - 1));
  const choose = (index: number) => { const row = rows[index]; if (row) { close(); row.run(); } };
  useEffect(() => { ref.current?.querySelector(`#command-result-${selected}`)?.scrollIntoView({ block: "nearest" }); }, [selected]);
  return <dialog ref={ref} className="v2-command-dialog" aria-label="Поиск и команды" onCancel={event => { event.preventDefault(); close(); }} onClick={event => { if (event.target === event.currentTarget) close(); }}><div className="v2-command-search"><Search size={21}/><input ref={input} placeholder="Материал, понятие или действие…" aria-label="Поиск материалов и команд" role="combobox" aria-controls="command-results" aria-expanded={true} aria-autocomplete="list" aria-activedescendant={rows.length ? `command-result-${selected}` : undefined} value={query} onChange={event => { setQuery(event.target.value); setActive(0); }} onKeyDown={event => { if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); setActive(previous => Math.max(0, Math.min(rows.length - 1, previous + (event.key === "ArrowDown" ? 1 : -1)))); } if (event.key === "Enter") { event.preventDefault(); choose(selected); } }}/><button className="icon-button" onClick={close} aria-label="Закрыть поиск"><X size={19}/></button></div><div id="command-results" role="listbox" aria-label="Результаты поиска">{rows.map((item,index)=><button role="option" aria-selected={index === selected} id={`command-result-${index}`} key={`${item.label}-${item.title}-${index}`} onClick={() => choose(index)} onPointerMove={() => setActive(index)}><item.icon size={18}/><span><strong>{item.title}</strong><small>{item.label}</small></span><ArrowRight size={15}/></button>)}{!rows.length ? <p className="v2-command-empty">Ничего не найдено. Попробуйте другое название.</p> : null}</div><footer><span>↑ ↓ выбрать · ↵ открыть</span><span>Esc закрыть</span></footer></dialog>;
}
